const oldSiteUrls = [
    "https://prasans.info/test-smtp-server/",
    "https://prasans.info/install-inconsolata-ttf-in-ubuntujaunty/",
    "https://prasans.info/first-post/",
    "https://prasans.info/tweaking-intellij-appearance-to-look-cool-in-ubuntu/",
    "https://prasans.info/enabling-yahoo-accounts-on-ubuntu/",
    "https://prasans.info/stop-halting-at-assertions/",
    "https://prasans.info/hadoop-version-in-aws-map-reduce/",
    "https://prasans.info/printing-multiple-divs-in-a-page/",
    "https://prasans.info/ftp-client-ubuntu/",
    "https://prasans.info/send-your-mail-later/",
    "https://prasans.info/install-custom-jar-files-in-samsung-corby-pro/",
    "https://prasans.info/test-your-controllers-modelattribute-methods/",
    "https://prasans.info/sax-parser-characters-method/",
    "https://prasans.info/play-age-of-empires-aoe-in-windows-7/",
    "https://prasans.info/add-edittexts-dynamically-and-retrieve-values-android/",
    "https://prasans.info/primary-key-onetoone-mapping-in-hibernate/",
    "https://prasans.info/wiring-android-wheel-widget-into-your-application/",
    "https://prasans.info/my-first-windows-7-theme/",
    "https://prasans.info/reloading-an-activity-in-android/",
    "https://prasans.info/writing-custom-tags-for-jstls/",
    "https://prasans.info/make_ntfs_write_mac_lion/",
    "https://prasans.info/configuring-context-name-for-an-applicationtomcat-war/",
    "https://prasans.info/running-windows-8-on-vm-on-mac-lion/",
    "https://prasans.info/scribblings-socket-io/",
    "https://prasans.info/slot-machine-effect-jquery/",
    "https://prasans.info/hamcrest-conflict-junit/",
    "https://prasans.info/link-your-sublime-text-2-instances-with-dropbox/",
    "https://prasans.info/utc-time-android-device-ntp-server-sync/",
    "https://prasans.info/handle-maxuploadsizeexceededexception-spring/",
    "https://prasans.info/whats-new-in-apple-passbook-ios7/",
    "https://prasans.info/setting-up-cucumber-jvm/",
    "https://prasans.info/wiring-jasmine2-with-phantom/",
    "https://prasans.info/re-running-testng-failed-tests/",
    "https://prasans.info/cross-site-http-requests/",
    "https://prasans.info/deploying-jekyll-blog-through-rake-script/",
    "https://prasans.info/skeleton-gradle-spring-mvc-app/",
    "https://prasans.info/add_ckeditor_to_rails_pipeline/",
    "https://prasans.info/integrating-netflix-hystrix-to-a-spring-application/",
    "https://prasans.info/making-https-call-using-apache-httpclient/",
    "https://prasans.info/testing-apiary-using-github-travis/",
    "https://prasans.info/url_generation_error_after_upgrading_rails/",
    "https://prasans.info/expanding_amazon_ebs_volumes/",
    "https://prasans.info/angular_resource_and_interceptors/",
    "https://prasans.info/capistrano_set_deployed_revision/",
    "https://prasans.info/store_function_inside_redux_store/",
    "https://prasans.info/post_errors_to_an_endpoint_angular/",
    "https://prasans.info/expire_session_after_timeout_spring/",
    "https://prasans.info/jest_test_toLocaleString_javasscript/",
    "https://prasans.info/card_slider_using_css3/",
    "https://prasans.info/using-network-call-in-react/",
    "https://prasans.info/soap-call-in-clojure-compojure-with-saaj/",
    "https://prasans.info/use flyway with leiningen/",
    "https://prasans.info/start-nginx-when-upstream-unavailable/",
    "https://prasans.info/add-redux-middleware-dynamically/",
    "https://prasans.info/logging-in-golang-projects/",
    "https://prasans.info/centralized-error-handling-express/",
    "https://prasans.info/ace-with-react/",
    "https://prasans.info/slicing-microservices/",
    "https://prasans.info/microservices-pattern-sagas/",
    "https://prasans.info/experience-with-aws-saa/",
    "https://prasans.info/castle-gorge-hiking-with-jhc/",
    "https://prasans.info/scaling-applications-using-microfrontends/",
    "https://prasans.info/me/",
    "https://prasans.info/success/",
    "https://prasans.info/talks/",
    "https://prasans.info/contact/",
    "https://prasans.info/",
    "https://prasans.info/search/"
];

const newSiteUrls = [
    "https://prasanna.dev",
    "https://prasanna.dev/about",
    "https://prasanna.dev/blog",
    "https://prasanna.dev/talks",
    "https://prasanna.dev/posts/first-post",
    "https://prasanna.dev/posts/test-smtp-server",
    "https://prasanna.dev/posts/install-inconsolata-ttf-in-ubuntujaunty",
    "https://prasanna.dev/posts/printing-multiple-divs-in-a-page",
    "https://prasanna.dev/posts/stop-halting-at-assertions",
    "https://prasanna.dev/posts/ftp-client-ubuntu",
    "https://prasanna.dev/posts/sax-parser-characters-method",
    "https://prasanna.dev/posts/hadoop-version-in-aws-map-reduce",
    "https://prasanna.dev/posts/test-your-controllers-modelattribute-methods",
    "https://prasanna.dev/posts/add-edittexts-dynamically-and-retrieve-values-android",
    "https://prasanna.dev/posts/play-age-of-empires-aoe-in-windows-7",
    "https://prasanna.dev/posts/primary-key-onetoone-mapping-in-hibernate",
    "https://prasanna.dev/posts/configuring-context-name-for-an-applicationtomcat-war",
    "https://prasanna.dev/posts/reloading-an-activity-in-android",
    "https://prasanna.dev/posts/writing-custom-tags-for-jstls",
    "https://prasanna.dev/posts/slot-machine-effect-jquery",
    "https://prasanna.dev/posts/make-ntfs-write-mac-lion",
    "https://prasanna.dev/posts/handle-maxuploadsizeexceededexception-spring",
    "https://prasanna.dev/posts/hamcrest-conflict-junit",
    "https://prasanna.dev/posts/scribblings-socket-io",
    "https://prasanna.dev/posts/link-your-sublime-text-2-instances-with-dropbox",
    "https://prasanna.dev/posts/setting-up-cucumber-jvm",
    "https://prasanna.dev/posts/whats-new-in-apple-passbook-ios7",
    "https://prasanna.dev/posts/utc-time-android-device-ntp-server-sync",
    "https://prasanna.dev/posts/wiring-jasmine2-with-phantom",
    "https://prasanna.dev/posts/re-running-testng-failed-tests",
    "https://prasanna.dev/posts/cross-site-http-requests",
    "https://prasanna.dev/posts/skeleton-gradle-spring-mvc-app",
    "https://prasanna.dev/posts/making-https-call-using-apache-httpclient",
    "https://prasanna.dev/posts/testing-apiary-using-github-travis",
    "https://prasanna.dev/posts/integrating-netflix-hystrix-to-a-spring-application",
    "https://prasanna.dev/posts/deploying-jekyll-blog-through-rake-script",
    "https://prasanna.dev/posts/add-ckeditor-to-rails-pipeline",
    "https://prasanna.dev/posts/url-generation-error-after-upgrading-rails",
    "https://prasanna.dev/posts/capistrano-set-deployed-revision",
    "https://prasanna.dev/posts/expanding-amazon-ebs-volumes",
    "https://prasanna.dev/posts/post-errors-to-an-endpoint-angular",
    "https://prasanna.dev/posts/angular-resource-and-interceptors",
    "https://prasanna.dev/posts/expire-session-after-timeout-spring",
    "https://prasanna.dev/posts/jest-test-toLocaleString-javasscript",
    "https://prasanna.dev/posts/store-function-inside-redux-store",
    "https://prasanna.dev/posts/card-slider-using-css3",
    "https://prasanna.dev/posts/flyway-migrations-in-lein-clojure",
    "https://prasanna.dev/posts/using-network-call-in-react",
    "https://prasanna.dev/posts/soap-call-in-clojure-compojure-with-saaj",
    "https://prasanna.dev/posts/start-nginx-when-upstream-unavailable",
    "https://prasanna.dev/posts/add-redux-middleware-dynamically",
    "https://prasanna.dev/posts/logging-in-golang-projects",
    "https://prasanna.dev/posts/centralized-error-handling-express",
    "https://prasanna.dev/posts/ace-with-react",
    "https://prasanna.dev/posts/scaling-applications-using-microfrontends",
    "https://prasanna.dev/posts/slicing-microservices",
    "https://prasanna.dev/posts/microservices-pattern-sagas",
    "https://prasanna.dev/posts/experience-with-aws-saa"
];

exports.handler = async (event: any) => {
    const requestPath: string = event.pathParameters.proxy;
    const pathMappings: Record<string, string> = {
        "ace-": "/posts/ace-"
    }
    const redirectPath = pathMappings[requestPath];
    const finalLocation = redirectPath ? redirectPath : "/";
    const response = {
        statusCode: 301,
        headers: {
            "Location" : `https://prasanna.dev${finalLocation}`
        }
    };
    return response;
};


export default oldSiteUrls;
